In [1]:
import numpy as np

In [2]:
l = range(1000000)

In [4]:
p = np.arange(1000000)

In [12]:
%time for i in range(1, 10): r = [x*2 for x in l]

Wall time: 877 ms


In [13]:
%time for i in range(10): d = p * 2

Wall time: 45.9 ms


In [14]:
# Multi-Dimensional Array

In [15]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
x = np.ones((4, 4))

In [17]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.empty((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.empty((10, 10))

array([[7.34483726e+223, 6.87055487e+228, 7.20535013e+159,
        1.08988615e+243, 7.48551512e+247, 1.19309411e+190,
        6.13331415e-154, 6.01347002e-154, 2.64935842e+180,
        1.23701832e+213],
       [2.17436711e+243, 5.16197848e+058, 1.27966302e-152,
        7.04101559e+199, 6.01334515e-154, 2.64935867e+180,
        6.01347002e-154, 7.77661508e+160, 6.02205281e+175,
        4.52177867e+217],
       [4.19339786e+228, 2.02740716e+267, 3.29975449e+180,
        3.64709873e+180, 7.15493659e-061, 6.01347002e-154,
        6.01116169e+175, 5.25084249e-090, 3.99255546e+252,
        2.19993033e-152],
       [1.14511381e+243, 6.24017181e-085, 1.30302352e+190,
        6.01347187e-154, 6.01347002e-154, 9.54868252e-090,
        4.76994842e+180, 3.99726796e+252, 7.52007076e+199,
        1.21906099e-152],
       [6.25901761e-085, 1.50879816e+267, 6.01394961e-154,
        6.01347002e-154, 6.01430546e+175, 8.54516092e+194,
        9.75394660e+199, 6.78578104e+212, 5.04304221e+223,
        6.0

In [20]:
l = [4, 5, 6, 7]
l

[4, 5, 6, 7]

In [21]:
l = np.array(l)

In [22]:
l

array([4, 5, 6, 7])

In [23]:
nice = np.arange(1, 100, 10)

In [24]:
nice

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [25]:
nice.shape

(10,)

In [30]:
x = np.zeros((3, 3))
x.shape

(3, 3)

In [29]:
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
x = np.arange(4)

In [32]:
x

array([0, 1, 2, 3])

In [34]:
x = np.ones((4, 4))

In [35]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
y = x.reshape((2, 8))

In [37]:
y

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
y = y.reshape((8, 2))

In [39]:
y

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
y.dtype

dtype('float64')

In [45]:
y.ndim

2

In [46]:
y.shape

(8, 2)

In [47]:
# Indexing and Slicing

In [48]:
y = np.ndarray(12)

In [49]:
y

array([1.38342300e-311, 2.47032823e-322, 0.00000000e+000, 0.00000000e+000,
       2.20687562e-312, 8.60952352e-072, 5.44639779e-090, 1.10587273e+165,
       6.54614800e-043, 5.18966919e+170, 3.99910963e+252, 1.23971686e+224])

In [50]:
y = np.arange(12)

In [51]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
 listArr = np.array([1, 7, 9, 8, 5])

In [53]:
listArr[listArr > 8]

array([9])

In [54]:
listArr[listArr >= 8]

array([9, 8])

In [55]:
listArr[[4, 1]]

array([5, 7])

In [56]:
# Fast Element-wise Array Func

In [57]:
listArr.max()

9

In [58]:
np.max(listArr)

9

In [59]:
list2 = np.array([4, 5, 10, 11, 1])

In [61]:
np.sqrt(listArr)

array([1.        , 2.64575131, 3.        , 2.82842712, 2.23606798])

In [62]:
listArr ** 2

array([ 1, 49, 81, 64, 25], dtype=int32)

In [64]:
np.power(listArr, 2)

array([ 1, 49, 81, 64, 25], dtype=int32)

In [65]:
np.maximum(list2, listArr)

array([ 4,  7, 10, 11,  5])

In [66]:
# Np.Where()

In [69]:
np.where(listArr[listArr>5], "hello", "nice")

array(['hello', 'hello', 'hello'], dtype='<U5')

In [70]:
salary = np.array([0, 1, 1000, 5000])

In [71]:
np.where(salary < 100, 25000, salary)

array([25000, 25000,  1000,  5000])

In [72]:
# Stats Method

In [73]:
x = np.array([1, 2, 3, 4, 5])

In [74]:
x.mean()

3.0

In [75]:
x.cumsum()

array([ 1,  3,  6, 10, 15], dtype=int32)

In [76]:
x.cumprod()

array([  1,   2,   6,  24, 120], dtype=int32)

In [77]:
x > 4

array([False, False, False, False,  True])

In [78]:
x.sum()

15

In [79]:
y = x > 2

In [80]:
y.sum()

3

In [81]:
y.any()

True

In [82]:
y.all()

False

In [83]:
y

array([False, False,  True,  True,  True])

In [84]:
y.sum()

3

In [85]:
y = y>3

In [86]:
y.sum()

0

In [87]:
y

array([False, False, False, False, False])

In [90]:
y.any()
# to check is any element is true

False

In [91]:
y.all() 
# to check is all elements are true

False

In [92]:
x.sort()

In [94]:
np.unique(x)

array([1, 2, 3, 4, 5])

In [95]:
x.sort(False)

In [96]:
x

array([1, 2, 3, 4, 5])

In [97]:
# File Input Output

In [98]:
x = [1, 4, 5, 7]
y = [8, 7, 9]

In [99]:
np.save('testx', x)

In [102]:
loadx = np.load('testx.npy')

In [103]:
loadx

array([1, 4, 5, 7])

In [104]:
np.savez('testxy', x, y)

In [105]:
loadxy = np.load('testxy.npz')

In [106]:
loadxy

In [120]:
# Linear Algebra

In [121]:
x = np.random.randn(3, 2)

In [122]:
y = np.random.randn(2, 3)

In [123]:
x.transpose()

array([[ 1.02444162,  0.44953148, -0.87841825],
       [ 0.36853732, -0.1147282 , -1.11076112]])

In [124]:
x.dot(y)

array([[ 0.04608409,  0.9824718 , -0.32281763],
       [-0.19942063,  0.21919262, -0.06643048],
       [-0.67096905, -1.4516891 ,  0.49306579]])

In [125]:
x.trace()

0.909713412584821

In [126]:
# Pseudo Random Number

In [127]:
# Biasness ko hatane ke liye random

In [128]:
np.random.seed(7)

In [130]:
y = np.random.normal(size=(3, 3))

In [131]:
y.flatten()

array([ 0.60049852, -0.62542897, -0.17154826,  0.50529937, -0.26135642,
       -0.24274908, -1.45324141,  0.55458031,  0.12388091])

In [132]:
# Concatenate

In [133]:
arr1 = np.array(([3, 4, 5], [4, 5, 6]))

In [134]:
arr1

array([[3, 4, 5],
       [4, 5, 6]])

In [137]:
arr2 = np.array(([3, 14, 5], [4, 5, 6]))

In [138]:
np.concatenate((arr1, arr2), axis = 1)

array([[ 3,  4,  5,  3, 14,  5],
       [ 4,  5,  6,  4,  5,  6]])

In [139]:
# Split

In [147]:
x = np.arange(1, 21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [148]:
np.split(x, [2, 5])

[array([1, 2]),
 array([3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])]

In [153]:
# Tile and Repeat

In [154]:
n = np.array([4, 5, 6])

In [157]:
np.repeat(n, 4)

array([4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6])

In [158]:
np.tile(n, 5)

array([4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6])